//
//  Constants.h
//  Dwight
//
//  Created by Afaq Hussain on 05/03/2014.
//  Copyright (c) 2014 Dynamic Logix. All rights reserved.
//

#ifndef Dwight_Constants_h
#define Dwight_Constants_h


#define PARSE_APPLICATION_ID        @"dwfPyU4zyg5On8gShWwHwquYDjYJlyzp1z6X35s1"
#define PARSE_CUSTOMER_KEY          @"LzLAtIlISgTuli3epiV5oIUIvFECyPRWUOw1YNLI"

#define FULL_NAME                   @"fullName"
#define FIRST_NAME                  @"firstName"
#define LAST_NAME                   @"lastName"
#define FACEBOOK_ID                 @"fbId"

#define DATA                        @"data"
#define UNIQUE_ID                   @"id"
#define FIRST_NAME_A                @"first_name"
#define LAST_NAME_A                 @"last_name"


#define USERNAME                    @"username"
#define FB_FRIENDS_PROFILE_PICTURES @"fbFriendsProfilePics"
#define NATIVE_FRIENDS              @"nativeFriendsIds"
#define BLOCKED_CONTACTS            @"blockedContacts"
#define PENDING_REQUESTS            @"pendingRequests"
#define USER                        @"user"
#define PROFILE_PICTURE             @"profilePicture"
#define NEW_FRIEND_REQUEST_NOTIFICATION     @"new_friend_notification"
#define SET_READY_FOR_RELOAD                @"set_ready_for_reload"
#define FRIEND_REQUEST_ACCEPTED_NOTIFICATION @"friend_request_accepted"
#define GROUP_SHOUT_OUT_AUTHORIZED @"group_shout_out_authorized"
#define GROUP_SHOUT_OUT_DEAUTHORIZED @"group_shout_out_deauthorized"
#define REFRESH_FRIENDS                 @"refresh_friends"
#define REFRESH_REQUESTS                @"refresh_requests"
#define GROUP_SHOUT_OUT_DONE            @"group_shout_out_sent"
#define FRIEND_REQUEST                  @"friend_request"
#define FRIEND                          @"friend"
#define GROUP                           @"group"
#define REQUEST                         @"Request"

#define OBJECT_ID                       @"objectId"


#define TALKIE_URL_STRING               @"http://www.google.com"
#define TALKIE_TERMS_URL_STRING         @"http://www.talkie-app.com/terms.htm"
#define TALKIE_PRIVACY_URL_STRING       @"http://www.talkie-app.com/privacy.htm"
#define TALKIE_FAQ_URL_STRING           @"http://support.talkie-app.com/?st_faq=talkie-walkie-faq"
#define TALKIE_ABOUT_URL_STRING         @"http://talkie-app.com/about.html"
#define TALKIE_NEW_FEATURES_URL_STRING  @"http://support.talkie-app.com/?page_id=260"

//Themes Info

#define BG_TILE                          @"bgtile"
#define IMAGE_SHAPE                      @"imageshape"
#define BG_MAIN                          @"bgmain"
#define THEME_NAME                       @"themename"
#define BTN_PULLDOWN                     @"btnpulldown"
#define BG_TOP_BAR                       @"bgtopbar"
#define BTN_SEARCH                       @"btnsearch"
#define BTN_ADD                          @"btnadd"
#define BTN_BELL                         @"btnbell"
#define BTN_SETTING                      @"btnsettings"
#define BTN_SHOUTOUT                     @"btnshoutout"
#define BTN_SHOUTOUT_SELECTED            @"btnshoutoutselected"
#define BTN_SHOUTOUT_SMALL               @"btnshoutoutsmall"
#define BTN_SINGLE_SHOUTOUT              @"btnsingleshoutout"
#define PROFILE_BORDER                   @"profileborder"
#define PROFILE_SEPARATOR                @"profileseparator"
#define PROFILE_ROUNDICON                @"profileroundicon"
#define BTN_AUDIO_BAR_UNSELECTED         @"btnaudiobarunselected"
#define BTN_AUDIO_BAR_UNSELECTED_SINGLE  @"btnaudiobarunselectedsingle"
#define BTN_AUDIO_BAR_SELECTED           @"btnaudiobarselected"
#define BTN_BACK                         @"btnback"
#define BG_SINGLE                        @"bgsingle"
#define BTN_BACK_SINGLE                  @"btnbacksingle"
#define BG_TOP_BAR_SINGLE                @"bgtopbarsingle"
#define BTN_SEND_SINGLE_SELECTED         @"btnsendsingleselected"
#define BTN_SEND_SINGLE_UNSELECTED       @"btnsendsingleunselected"
#define BTN_PLAY_UNSELECTED              @"btnplayunselected"
#define BTN_PLAY_SELECTED                @"btnplayselected"
#define PROFILE_SEPARATORSINGLE          @"profileseparatorsingle"
#define BTN_PULL_DOWN_SINGLE             @"btnpulldownsingle"
#define BG_HALF_CIRCLE_SINGLE            @"bghalfcirclesingle"
#define PROFILE_BORDER_SINGLE            @"profilebordersingle"
#define BTN_BACK_GROUP                   @"btnbackgroup"
#define BG_TOP_BAR_GROUP                 @"bgtopbargroup"
#define PROFILE_BORDER_GROUP             @"profilebordergroup"
#define BTN_SEND_GROUP_SELECTED          @"btnsendgroupselected"
#define BTN_SEND_GROUP_UNSELECTED        @"btnsendgroupunselected"
#define BG_GROUP                         @"bggroup"
#define GROUP_SEND_BAR_UNSELECTED        @"btngroupsendbarunselected"
#define GROUP_SEND_BAR_SELECTED          @"btngroupsendbarselected"
#define BTN_SHOUT_OUT_GROUP_UNSELECTED   @"btnshoutoutgroupunselected"
#define BTN_SHOUT_OUT_GROUP_SELECTED     @"btnshoutoutgroupselected"
#define COLOR_SINGLE_SEND_SELECTED       @"colorsinglesendselected"
#define COLOR_SINGLE_SEND_UNSELECTED     @"colorsinglesendunselected"
#define COLOR_GROUP_SEND_SELECTED        @"colorgroupsendselected"
#define COLOR_GROUP_SEND_UNSELECTED      @"colorgroupsendunselected"
#define DROP_DOWN_NAV_BAR1               @"dropdownnavbar1"
#define DROP_DOWN_NAV_BAR2               @"dropdownnavbar2"
#define DROP_DOWN_BTN_BACK               @"dropdownbtnback"
#define AUDIO_MESSAGES                   @"audiomessages"
#define AUDIO_FILE_NAME                  @"audiofilename"
#define FBF_SEGMENT0_UNSELECTED          @"fbfsegment0unselected"
#define FBF_SEGMENT1_UNSELECTED          @"fbfsegment1unselected"
#define FBF_SEGMENT2_UNSELECTED          @"fbfsegment2unselected"
#define FBF_SEGMENT0_SELECTED            @"fbfsegment0selected"
#define FBF_SEGMENT1_SELECTED            @"fbfsegment1selected"
#define FBF_SEGMENT2_SELECTED            @"fbfsegment2selected"
#define FBF_BTN_ADD                      @"fbfbtnadd"
#define FBF_BTN_ADDED                    @"fbfbtnadded"
#define FBF_BTN_PENDING                  @"fbfbtnpending"
#define FBF_BTN_ACCEPT                   @"fbfbtnaccept"
#define MANAGE_FRIENDS_BTN_UNFRIEND      @"managebtnunfriend"
#define MANAGE_FRIENDS_BTN_UNBLOCK       @"managebtnunblock"
#define MANAGE_FRIENDS_BTN_BLOCK         @"managebtnblock"
#define FIND_FRIENDS_SEG0_SELECTED       @"findfriendseg0selected"
#define FIND_FRIENDS_SEG0_UNSELECTED     @"findfriendseg0unselected"
#define FIND_FRIENDS_SEG1_SELECTED       @"findfriendseg1selected"
#define FIND_FRIENDS_SEG1_UNSELECTED     @"findfriendseg1unselected"

#endif